### ISSUE TITLE
Is the `Strings` section on the `Direct Buffer` page correct?

### ISSUE THREAD

**Issue by yafetn** [real-logic/aeron-cookbook-code#211]
Hi,

I was reading [this section](https://aeroncookbook.com/agrona/direct-buffer/#strings) and I'm a little confused by the difference in the `putStringAscii` and `putStringWithoutLengthAscii` methods as shown. There's a part that says

`
An example of a putStringWithoutLengthAscii with the same 12 byte ASCII string, with bytes 1 through 11 holding the content:
`
Should it be `...bytes 0 through 11 holding the content` instead?

**Comment by eleventy7** [comment]
Yes, I believe that you are correct. I will address this; thank you!
