### ISSUE TITLE
 Align the SimplestCase single host sample with the multi host example.

### ISSUE THREAD

**Issue by michaelszymczak** [real-logic/aeron-cookbook-code#239]
Sometimes the sample code results in an error when the counter is not yet ready, plus some minor improvement when closing the resources and interacting with the archive. The multi host example does not suffer from the issues fixed here.

Fixed in https://github.com/real-logic/aeron-cookbook-code/pull/235/

**Comment by eleventy7** [comment]
Thank you; that is now merged.
